# Données sur les faits divers

### Notes :
Erreur 403 sur le site de Legifrance -> nécessicité de passer par l'API, avec une inscription --> barbant

Pistes possibles : utiliser des données sur les pages Wikipedia suivantes :

https://fr.wikipedia.org/wiki/Enqu%C3%AAtes_criminelles_:_le_magazine_des_faits_divers

Épisodes d'enquêtes sur des affaires criminelles -> à faire : trier les faits divers français et étrangers

https://fr.wikipedia.org/wiki/Liste_d'affaires_criminelles_fran%C3%A7aises_depuis_1900

Faits divers recensés sur Wikipedia\
Nature des données :\
tableaux triés par décénies\
plage de données : 1900 à 2020\
Colonnes d'intérêt : Départements et résumés\
Départements : propres\
Résumés : à extraire : les dates (JJ mois AAAA) \
Limite : gros faits divers médiatisés, probablement aucun rapport avec la météo...

## Récupération et nettoyage des données de la page Wikipédia sur les affaires criminelles

### Récupération des données

In [1]:
### Récupération des données sur la page Wikipédia

import requests

url = "https://fr.wikipedia.org/wiki/Liste_d'affaires_criminelles_fran%C3%A7aises_depuis_1900"

req = requests.get(url, headers={"User-Agent":"School Data Science Project"})
print(req)

<Response [200]>

In [2]:
### Transformation en fichier exploitable
import bs4

request_text = req.content
page = bs4.BeautifulSoup(request_text, "lxml")
print(page)

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard skin-underline-clientpref-browser" dir="ltr" lang="fr">
<head>
<meta charset="utf-8"/>
<title>Liste d'affaires criminelles françaises depuis 1900 — Wikipédia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard skin-underline-clientpref-browser";var cookie=document.cookie.match(/(?:^|; )frwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":[",\t."," \t,"],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","janvier","février","mars","avril","mai","juin","juillet","août","septembre","octobre","novembre","décembre"],"wgRequestId":"381e1f75-73ce-4c05-be82-a3e4b29425dd","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Liste_d'affaires_criminelles_françaises_depuis_1900","wgTitle":"Liste d'affaires criminelles françaises depuis 1900","wgCurRevisionId":240798980,"wgRevisionId":240798980,"wgArticleId":498241,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Article contenant un lien mort","Article à référence souhaitée","Article contenant un appel à traduction en anglais","Page utilisant une présentation en colonnes avec un nombre fixe de colonnes","Page utilisant un modèle Bases inactif","Article utilisant le modèle Dictionnaires inactif","Page utilisant le modèle Autorité inactif","Portail:Droit français/Articles liés","Portail:Droit/Articles liés","Portail:Société/Articles liés","Portail:France/Articles liés","Portail:Europe/Articles liés","Portail:Criminologie/Articles liés","Portail:Sciences humaines et sociales/Articles liés","Affaire criminelle en France","Liste en rapport avec le droit français","Disparition","Liste d'affaires criminelles"],"wgPageViewLanguage":"fr","wgPageContentLanguage":"fr","wgPageContentModel":"wikitext","wgRelevantPageName":"Liste_d'affaires_criminelles_françaises_depuis_1900","wgRelevantArticleId":498241,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgCiteReferencePreviewsActive":true,"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgMediaViewerDesktopVue":false,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"fr","pageLanguageDir":"ltr","pageVariantFallbacks":"fr"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":true,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":200000,"wgParsoidHtmlVersion":"2.8.0","parsermigration-parsoid":true,"wgPageAssessments":{"Criminologie":{"class":"BD","importance":"élevée"},"Droit":{"class":"BD","importance":"faible"},"France":{"class":"BD","importance":"faible"},"Société":{"class":"BD","importance":"faible"}},"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":true,"wgWikibaseItemId":"Q3242844","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"wgCheckUserClientHintsInEditRequest":true};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.parsoid.styles":"ready","ext.cite.styles":"ready","ext.wikimediamessages.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","site","mediawiki.page.ready","jquery.tablesorter","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ArchiveLinks","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","ext.wikimediaCustomizations.donorAccountCreation","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.readerExperiments/preferredSources"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=fr&amp;modules=ext.cite.parsoid.styles%7Cext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=fr&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=fr&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.47.0-wmf.24" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="width=1120" name="viewport"/>
<meta content="Liste d'affaires criminelles françaises depuis 1900 — Wikipédia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//thumb.wikimedia.org" rel="preconnect"/>
<link href="/w/index.php?title=Liste_d%27affaires_criminelles_fran%C3%A7aises_depuis_1900&amp;action=edit" rel="alternate" title="Modifier" type="application/x-wiki"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipédia (fr)" type="application/opensearchdescription+xml"/>
<link href="//fr.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://fr.wikipedia.org/wiki/Liste_d%27affaires_criminelles_fran%C3%A7aises_depuis_1900" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.fr" rel="license"/>
<link href="/w/index.php?title=Sp%C3%A9cial:Modifications_r%C3%A9centes&amp;feed=atom" rel="alternate" title="Flux Atom de Wikipédia" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch"/>
<link href="auth.wikimedia.org" rel="dns-prefetch"/>
</head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-Liste_d_affaires_criminelles_françaises_depuis_1900 rootpage-Liste_d_affaires_criminelles_françaises_depuis_1900 skin-vector-2022 action-view">
<div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region"></div><a class="mw-jump-link" href="#bodyContent">Aller au contenu</a>
<div class="vector-header-container">
<header class="vector-header mw-header no-font-mode-scale">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Menu principal">
<input aria-haspopup="true" aria-label="Menu principal" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Menu principal</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Menu principal</div>
<button aria-label="Move Menu principal to sidebar" class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">déplacer vers la barre latérale</button>
<button aria-label="Hide Menu principal" class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">masquer</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Wikip%C3%A9dia:Accueil_principal" title="Accueil général [z]"><span>Page d’accueil</span></a></li><li class="mw-list-item" id="n-thema"><a href="/wiki/Portail:Accueil" title="Regroupements d'articles par thématiques"><span>Portails thématiques</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Sp%C3%A9cial:Page_au_hasard" title="Affiche un article au hasard [x]"><span>Article au hasard</span></a></li><li class="mw-list-item" id="n-contact"><a href="/wiki/Wikip%C3%A9dia:Contact" title="Qui contacter"><span>Contact</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-Contribuer" id="p-Contribuer">
<div class="vector-menu-heading">
		Contribuer
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-aboutwp"><a href="/wiki/Aide:D%C3%A9buter" title="Guide pour apprendre à contribuer à Wikipédia"><span>Débuter sur Wikipédia</span></a></li><li class="mw-list-item" id="n-help"><a href="/wiki/Aide:Accueil" title="Accès à l’aide"><span>Aide</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikip%C3%A9dia:Accueil_de_la_communaut%C3%A9" title="À propos du projet, ce que vous pouvez faire, où trouver les informations"><span>Communauté</span></a></li><li class="mw-list-item" id="n-specialpages"><a accesskey="q" href="/wiki/Sp%C3%A9cial:Pages_sp%C3%A9ciales" title="Outils pour contribuer à Wikipédia [q]"><span>Pages spéciales</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Sp%C3%A9cial:Modifications_r%C3%A9centes" title="Liste des modifications récentes sur le wiki [r]"><span>Modifications récentes</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Wikip%C3%A9dia:Accueil_principal">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/wikipedia.png" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipédia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-fr.svg" style="width: 7.4375em; height: 1.125em;"/>
<img alt="l'encyclopédie libre" class="mw-logo-tagline" height="13" src="/static/images/mobile/copyright/wikipedia-tagline-fr.svg" style="width: 7.5em; height: 0.8125em;" width="120"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Sp%C3%A9cial:Recherche" title="Rechercher sur Wikipédia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search cdx-button__icon"></span>
<span>Rechercher</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Rechercher sur Wikipédia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Rechercher sur Wikipédia" spellcheck="false" title="Rechercher sur Wikipédia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Spécial:Recherche"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Rechercher</button>
</form>
</div>
</div>
</div>
<nav aria-label="Outils personnels" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Apparence" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Modifier l'apparence de la taille, de la largeur et de la couleur de la police de la page">
<input aria-haspopup="true" aria-label="Apparence" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Apparence</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item vector-menu-item--collapsible" id="pt-sitesupport-2"><a class="" data-mw-donate-attempt="top_link" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=fr.wikipedia.org&amp;uselang=fr"><span>Faire un don</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-createaccount-2"><a class="" data-mw-interface="" href="/w/index.php?title=Sp%C3%A9cial:Cr%C3%A9er_un_compte&amp;returnto=Liste+d%27affaires+criminelles+fran%C3%A7aises+depuis+1900" title="Nous vous encourageons à créer un compte utilisateur et vous connecter ; ce n’est cependant pas obligatoire."><span>Créer un compte</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-login-2"><a accesskey="o" class="" data-mw-interface="" href="/w/index.php?title=Sp%C3%A9cial:Connexion&amp;returnto=Liste+d%27affaires+criminelles+fran%C3%A7aises+depuis+1900" title="Nous vous encourageons à vous connecter ; ce n’est cependant pas obligatoire. [o]"><span>Se connecter</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out vector-user-links-dropdown--collapsible" id="vector-user-links-dropdown" title="Plus d’options">
<input aria-haspopup="true" aria-label="Outils personnels" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-userAvatar mw-ui-icon-wikimedia-userAvatar cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Outils personnels</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal" id="p-personal" title="Menu utilisateur">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item vector-menu-item--collapsible" id="pt-sitesupport"><a class="" data-mw-donate-attempt="top_link" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=fr.wikipedia.org&amp;uselang=fr"><span class="vector-icon mw-ui-icon-heart mw-ui-icon-wikimedia-heart cdx-button__icon"></span>
<span>Faire un don</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-createaccount"><a class="" data-mw-interface="" href="/w/index.php?title=Sp%C3%A9cial:Cr%C3%A9er_un_compte&amp;returnto=Liste+d%27affaires+criminelles+fran%C3%A7aises+depuis+1900" title="Nous vous encourageons à créer un compte utilisateur et vous connecter ; ce n’est cependant pas obligatoire."><span class="vector-icon mw-ui-icon-userAvatar mw-ui-icon-wikimedia-userAvatar cdx-button__icon"></span>
<span>Créer un compte</span></a>
</li>

### Récupération des tableaux

In [3]:
### On récupère tous les tableaux de la page, on triera plus tard selon les dates

tableaux = page.find_all('table', {'class':'wikitable sortable'})
print(len(tableaux))

24

In [4]:
### Transformation en listes de string pour manipuler les tableaux

faitsDiv = list()
for tableau in tableaux :
    table_body = tableau.find('tbody')
    rows = table_body.find_all('tr')
    liste = list()
    for row in rows:
        cols = row.find_all('td')
        cols = [ele.text.strip() for ele in cols]
        if len(cols) > 0 : 
            liste.append(cols)
    faitsDiv.append(liste)

faitsDiv

[[['1905 - 1908',
   'Drôme',
   'Chauffeurs de la Drôme',
   "De 1905 à 1908 dans la Drôme, actes de brigandage suivis d'assassinats par Urbain Liottard, Octave David et Louis Berruyer.",
   'Urbain Liottard est condamné le 10 juillet 1909 à la peine de mort, Octave David à la peine de mort, Louis Berruyer à la peine de mort par les assises de la Drôme. Guillotinés le 22 septembre 1909 à Valence.'],
  ['1907',
   'Seine',
   'Affaire Soleilland',
   'Le 31 janvier 1907 à Paris, meurtre de Marthe Erbelding, onze ans, après avoir été violée et poignardée.',
   'Albert Soleilland est condamné le 23 juillet 1907 à la peine de mort. Gracié, il meurt au bagne en 1920 après 13 ans de détention.'],
  ['1907',
   'Gironde',
   'Crime de Langon',
   "Le 6 février 1907 à Langon, assassinat crapuleux d'un agent d'assurance, Jean-Théodore Monget étranglé avec une serviette, commis par Jean-Eugène Branchery et Henri Parrot.",
   'Jean-Eugène Branchery est condamné le 29 février 1908 à la peine de mort, Henri Parrot à la peine de mort par les assises de la Gironde. Ils sont graciés le 18 juillet 1908. Suites inconnues.'],
  ['1909',
   'Seine-et-Oise',
   'Affaire Bourette',
   'Le 22 octobre 1909 au Vésinet, empoisonnement du ténor belge Jules Godart par Marie Bourette.',
   'Marie Bourette est condamnée le 13 juillet 1910 aux travaux forcés à perpétuité par les assises de Seine-et-Oise. Suites inconnues.'],
  ['1910',
   'Seine',
   'Affaire Liabeuf',
   "Le 8 janvier 1910 à Paris, assassinat d'un policier par Jean-Jacques Liabeuf, cordonnier estimant avoir été condamné à tort pour proxénétisme.",
   'Jean-Jacques Liabeuf est condamné le 4 mai 1910 à la peine de mort par les assises de la Seine. Exécuté par décapitation le 1er juillet 1910 à Paris.'],
  ['1910',
   'Seine-Inférieure',
   'Affaire Durand',
   "Le 9 septembre 1910 au Havre, meurtre de Louis Dongé au cours d'une rixe lors d'une grève.",
   'Jules Durand est condamné le 25 novembre 1910 à la peine de mort par les assises de Seine-Inférieure. Gracié et libéré le 15 février 1911 après 1 an de détention.']],
 [['1911-1912',
   "Paris, Val-de-Marne, Val-d'Oise, Oise",
   'La Bande à Bonnot',
   'Série de braquages et de meurtres.',
   'Les méfaits de la bande inspirent notamment un film, sorti en 1968.'],
  ['1913',
   'Loire-Inférieure',
   'Affaire Marcel Redureau',
   "Meurtre de sept personnes le 30 septembre 1913, dans le village de Bas-Briacé, commune du Landreau. Un adolescent de quinze ans, Marcel Redureau, avoue être l'auteur des faits[1].",
   "Condamné à 20 ans de prison, Marcel Redureau meurt de la tuberculose en 1916 à Villeneuve-sur-Lot, à l'âge de 17 ans[2].\nL'affaire intéresse notamment Gide, qui publie à son sujet en 1930 un recueil de documents."],
  ['1914',
   'Finistère',
   'Affaire Cadiou',
   "Le 4 février 1914, le corps de Louis Cadiou est découvert dans un bois à 400 m de l'usine dont il est l'actionnaire.",
   "Jugé cinq ans après les faits, l'ingénieur Louis Pierre est acquitté le 31 octobre 1919 par onze voix sur douze. Affaire non élucidée en 2026."],
  ['1914',
   'Paris',
   'Affaire Caillaux',
   "Assassinat du directeur du Figaro, Gaston Calmette, le 16 mars 1914, par l'épouse de Joseph Caillaux, irritée par une campagne de presse dirigée contre son mari, ministre des Finances du gouvernement Doumergue.",
   'Le président de la République fait une déposition au cours du procès. Henriette Caillaux sera finalement acquittée, son crime étant considéré comme un crime passionnel.'],
  ['1914',
   'Paris',
   'Affaire Villain',
   'Assassinat du leader socialiste Jean Jaurès, le 31 juillet 1914 par Raoul Villain.',
   'Jugé cinq ans après les faits, Raoul Villain est acquitté le 29 mars 1919 par onze voix sur douze, tandis que la veuve de Jaurès est condamnée aux dépens (paiement des frais du procès).'],
  ['1915-1919',
   'Yvelines',
   'Affaire Landru',
   'Assassinat de onze femmes entre février 1915 et janvier 1919 à Vernouillet et à Gambais par Henri-Désiré Landru.',
   "L'affaire inspire un film en 1947 de Charlie Chaplin, et plus explicitement Landru (film, 1963) de Claude Chabrol en 1963."],
  ['1916',
   'Algérie française',
   'Affaire de Foucauld',
   'Assassinat de Charles de Foucauld, 58 ans, prêtre ermite, le 1er décembre 1916 dans le Sahara algérien par des pillards.',
   ''],
  ['1917-1922',
   'Corrèze',
   'Affaire du corbeau de Tulle',
   "Vague de lettres anonymes signées «\xa0L'Œil de tigre\xa0» et dénonçant les faits et gestes des uns et des autres, a causé un mort en décembre 1921 et des suicides.",
   "Cette affaire a un retentissement national. Piégée lors d'une dictée collective, Angèle Laval est condamnée. Elle meurt le 16 novembre 1967, à l'âge de 81 ans. L'affaire inspire Le Corbeau (film, 1943) de Henri-Georges Clouzot."],
  ['1920-1922',
   'Paris',
   'Affaire Bassarabo',
   "Assassinat du commissionnaire Georges Bassarabo, le 31 juillet 1920, dont on a découvert le corps dans une malle expédiée à Nancy. Son épouse, née Louise Grouès, écrivaine et militante féministe connue sous le nom de plume d'Héra Mirtel, défendue par Vincent de Moro-Giafferri, est jugée en juin 1922 aux assises de la Seine en même temps que sa fille, Paule Jacques. À l'issue d'un procès riche en coups de théâtre, Paule Jacques est acquittée, et sa mère, bénéficiant de circonstances atténuantes, condamnée à vingt ans de travaux forcés. Elle meurt à Rennes le 21 mars 1931.",
   'Le crime et le procès firent la une de la presse, en raison de la personnalité de l\'accusée et de l\'étrangeté du procédé dit de la "malle sanglante". Plusieurs ouvrages et documentaires télévisés s\'en font l\'écho.']],
 [['1922-1929',
   'Hérault',
   'Affaire Laget',
   'Meurtres par empoisonnement perpétrés par Pierre Laget, sur sa première épouse, le 28 mai 1922, puis sur sa tante, en 1923, ainsi que sur sa seconde épouse, le 12 août 1929. Il tente également de tuer sa sœur par empoisonnement, entre décembre 1929 et février 1930.',
   'L\'affaire inspire un livre paru en 2015\xa0: "L\'affaire Laget, une énigme qui bouleversa le Midi de la France"[3].'],
  ['1923',
   'Finistère\xa0?, Région parisienne\xa0?',
   'Affaire Seznec',
   "Disparition du conseiller général Pierre Quémeneur dans la nuit du 25 au 26 mai 1923, lors d'un voyage de Rennes à Paris. Guillaume Seznec qui l'accompagnait est condamné en 1924 aux travaux forcés à perpétuité pour meurtre et faux en écriture.",
   "À la suite du jugement, quinze requêtes en révision déposées entre 1925 et 2026. L'affaire inspire à Denis Langlois un livre, L'Affaire Seznec (Plon, 1988) qui recevra en 1989 le Prix des Droits de l'homme et donnera lieu en 1993 à une adaptation en téléfilm d'Yves Boisset, avec Christophe Malavoy dans le rôle de Guillaume Seznec."],
  ['1925',
   'Paris',
   'Affaire Berger',
   "Assassinat d'Ernest Berger, trésorier de l'Action française, le 26 mai 1925, dans la station de métro Saint-Lazare, d'une balle dans le dos par la jeune militante anarchiste Maria Bonnefoy, prétendument pour sa ressemblance avec Charles Maurras.",
   'Elle sera déclarée atteinte de démence totale.'],
  ['1925',
   'Bouches-du-Rhône',
   'Affaire Sarrejani',
   "Meurtre par un avocat escroc de l'un de ses complices et de la maîtresse de celui-ci le 20 août 1925 dans la région d'Aix-en-Provence.",
   "L'affaire inspire Le Trio infernal, sorti en 1974."],
  ['1926',
   'Paris',
   'Affaire Schwartzbard',
   'Assassinat de Symon Petlioura, dirigeant socialiste et indépendantiste ukrainien, le 25 mai 1926 par le militant révolutionnaire Sholem Schwartzbard.',
   ''],
  ['1927-1949',
   'Vienne',
   'Affaire Besnard',
   "Mort, à Loudun, de plusieurs personnes dont on a soupçonné qu'elles auraient été empoisonnées à l'arsenic par l'une de leurs parentes ou relations, Marie Besnard.",
   ''],
  ['1928',
   'Haute-Vienne',
   'Affaire Barataud',
   'Meurtre à Berneuil le 12 janvier 1928 du chauffeur de taxi Etienne Faure, puis à Limoges de Bertrand Peynet, son amant de 19 ans.',
   'Charles Barrataud est condamné le 7 juin 1929 aux travaux forcés à perpétuité, libéré en 1948 après 20 ans de bagne.'],
  ['1928',
   'Paris',
   'Affaire Landy',
   'Meurtre de Paul Grappe, abattu par son épouse Louise Landy le 21 juillet 1928.',
   "L'affaire inspire Nos années folles d'André Téchiné, sorti en 2017."],
  ['1928',
   'Alpes-de-Haute-Provence',
   'Tuerie de Valensole',
   'Assassinat à Valensole de cinq personnes dont deux enfants dans une ferme isolée par Alexandre Ughetto et Joseph Mucha, 18 et 16 ans.',
   "Alexandre Ughetto est condamné à mort et exécuté le 24 janvier 1930. Joseph Mucha reçoit vingt ans de détention et dix ans d'interdiction de séjour sur le territoire."]],
 [['1932',
   'Paris, Seine',
   'Affaire Gorgulov',
   'Assassinat du président Paul Doumer le 6 mai 1932 par Paul Gorgulov.',
   ''],
  ['1933',
   'Sarthe',
   'Affaire Papin',
   'Meurtre par deux sœurs, Christine et Léa Papin, employées de maison, de leur patronne et de sa fille le 2 février 1933 au Mans.',
   "L'affaire, dans laquelle on a pu voir un drame lié à la lutte des classes sociales, aurait notamment inspiré la pièce Les Bonnes de Jean Genet. Elle inspire également le film Les Blessures assassines et, moins directement le film La Cérémonie de Claude Chabrol."],
  ['1933',
   'Paris, Seine',
   'Affaire Nozière',
   'Empoisonnement des membres de sa famille par Violette Nozière, le 21 août 1933, entraînant la mort de son père Baptiste Nozière.',
   "L'affaire inspire, en 1977, un film de Claude Chabrol."],
  ['1933',
   'Paris, Seine',
   'Affaire Dufrenne',
   "Meurtre d'Oscar Dufrenne, directeur du Palace dans son bureau le 24 septembre 1933.",
   '«\xa0Le crime du Palace\xa0».'],
  ['1934',
   'Haute-Savoie',
   'Affaire Stavisky',
   "Mort dans des circonstances suspectes d'Alexandre Stavisky, le 8 janvier 1934 à Chamonix.",
   "L'affaire entraîne un scandale politico-financier et contribue à la chute du gouvernement Camille Chautemps et au déclenchement des émeutes antiparlementaires du 6 février 1934. Elle inspire Stavisky (film) d'Alain Resnais, sorti en 1974."],
  ['1934',
   'Martinique',
   'Affaire Aliker',
   'André Aliker, militant communiste martiniquais, est retrouvé mort ligoté le 12 janvier 1934 à Case-Pilote.',
   'Sa mort est un détonateur pour le mouvement ouvrier en Martinique.'],
  ['1934',
   'Bouches-du-Rhône',
   'Affaire Tchernozemski',
   'Assassinat du roi de Yougoslavie Alexandre Ier par le nationaliste bulgare Vlado Tchernozemski, le 9 octobre 1934 à Marseille.',
   'Louis Barthou ministre des Affaires étrangères, blessé au bras par un tir ami meurt peu après.'],
  ['1934',
   'Var',
   'Affaire Sasia',
   'Meurtre de quatre personnes dans le Haut-Var.',
   "Giuseppe Sasia, surnommé «\xa0le tueur de bergers\xa0» ou «\xa0le tueur du Haut-Var\xa0» assassine quatre personnes en quelques mois. Il avoue les meurtres avant de n'en reconnaître que deux. Condamné en décembre 1935, il est guillotiné à Draguignan le 17 février 1936."],
  ['1935',
   'Seine-et-Oise',
   'Affaire Tharault',
   'Meurtre du cycliste Henri Pélissier, abattu par sa maîtresse Camille Tharault le 1er mai 1935 à Dampierre-en-Yvelines.',
   ''],
  ['1937',
   'Seine-et-Oise, Seine-et-Marne',
   'Affaire Weidmann',
   'Enlèvements et meurtres de six personnes, du 21 juillet au 27 novembre 1937 par Eugène Weidmann.',
   'Dernier condamné à avoir été guillotiné en public en France.'],
  ['1938',
   'Ille-et-Vilaine',
   'Affaire Pilorge',
   "Meurtre d'un jeune Mexicain, Nestor Escudero, par Maurice Pilorge le 6 août 1938 dans un hôtel de Dinard. Pilorge est guillotiné à Rennes le 4 février 1939.",
   "L'affaire, qui semble avoir marqué l'écrivain Jean Genet, est mentionnée\xa0– du moins le nom de Pilorge –, notamment dans Notre-Dame des Fleurs."],
  ['1940-1943',
   'Manche',
   'Affaire Giraud',
   'Vingt-sept avortements illégaux dans la région de Cherbourg par Marie-Louise Giraud.',
   'Elle est la seule femme – mais non la seule personne[4] – à avoir été guillotinée pour ce motif en France. Elle inspire le film Une affaire de femmes de Claude Chabrol. À la suite de cette affaire, une loi paraît qui promulgue que seul un médecin peut prescrire un avortement.']],
 [['1941',
   'Drôme',
   'Affaire Dormoy',
   "Assassinat de Marx Dormoy, homme politique, par Ludovic Guichard, Yves Moynier et Maurice Vaillant, d'anciens cagoulards, avec la complicité d'une comédienne, Annie Mourraille qui a servi d'«\xa0appât\xa0». C'est la mort de Maurice Vaillant, avec deux complices, dans l'explosion de leur bombe destinée à un acte terroriste antisémite, à Nice, dans la nuit du 14 au 15 août 1941, qui met les enquêteurs sur la bonne piste.",
   'Les prévenus ne seront jamais jugés, et seront libérés de la prison de Largentière, le 23 janvier 1943, par des militaires allemands.'],
  ['1941',
   'Paris',
   'Affaire Gitton',
   "Assassinat de Marcel Gitton, homme politique le 5 septembre 1941 dans une rue des Lilas par Marcel Cretagne, membre du détachement Valmy, groupe d'action sous la direction du Parti communiste visant notamment à exécuter les «\xa0traîtres\xa0».",
   ''],
  ['1941-1944',
   'Paris',
   'Affaire Petiot',
   "Assassinat de vingt-sept personnes durant l'Occupation, par le docteur Marcel Petiot.",
   "L'affaire inspire notamment Docteur Petiot (film), sorti en 1990."],
  ['1941-1944',
   'Paris',
   'Affaire de la Gestapo française de la rue Lauriston',
   "Beaucoup de résistants torturés dans cette maison durant l'Occupation, par des français, agents auxiliaires de la Gestapo du groupe Bonny-Lafont.",
   'Période de la Seconde Guerre mondiale. Traduits en justice en décembre 1944, ils sont condamnés à mort et fusillés.'],
  ['1943\xa0?',
   'Moselle',
   'Affaire Moulin',
   'Jean Moulin, haut fonctionnaire et résistant français, fut torturé par le chef de la Gestapo de Lyon, Klaus Barbie, avant de mourir de ses blessures dans le train qui le transporte en Allemagne peu avant le passage de la frontière.',
   "Période de la Seconde Guerre mondiale. La date officielle de sa mort le 8 juillet 1943, laisse planer un doute. Le lendemain, le corps d’«\xa0un ressortissant français décédé en territoire allemand\xa0» — présumé être Jean Moulin — est rapatrié à Paris, gare de l'Est et aussitôt incinéré, et l'urne transférée au Panthéon ne contient que les «\xa0cendres présumées du décédé\xa0». Son tortionnaire, Klaus Barbie, mourra en prison près de 50 ans plus tard."],
  ['1943',
   'Paris',
   'Affaire Ritter',
   'Julius Ritter, colonel SS qui supervisait en France le STO est tué le 28 septembre 1943 par une équipe des FTP-MOI.',
   ''],
  ['1944',
   'France',
   'Affaire Barbie',
   "Klaus Barbie, criminel de guerre allemand, officier SS sous le régime nazi, en fuite durant plus de 40 ans, a finalement été extradé de Bolivie vers la France et est reconnu coupable de dix-sept crimes contre l'humanité et le condamne à la prison à perpétuité «\xa0pour la déportation de centaines de Juifs de France et notamment l'arrestation, le 6 avril 1944, de 44 enfants juifs et de 7 adultes à la maison d'enfants d'Izieu et leur déportation à Auschwitz. Barbie meurt en prison en 1991.",
   '«\xa0Le boucher de Lyon\xa0»'],
  ['1944',
   'Paris',
   'Affaire Bernardy de Sigoyer',
   'Assassinat de Jeanine Kergot par son époux Alain de Bernardy de Sigoyer, le 29 mars 1944.',
   ''],
  ['1944',
   'Manche',
   'Affaire Whitfield',
   "Viol d'une jeune réfugiée polonaise dans une ferme normande de Sainte-Mère-Église par Clarence Whitfield, GI noir américain, quelques jours après le débarquement du 6 juin 1944.",
   'Whitfield est condamné et pendu.'],
  ['1944',
   'Allier',
   'Affaire Zay',
   'Assassinat de Jean Zay, avocat le 20 juin 1944 par Charles Develle, responsable de la sécurité de la Milice.',
   'Interpellé à Naples, jugé en février 1953, Develle est condamné aux travaux forcés à perpétuité par le tribunal militaire de Lyon, puis libéré deux ans plus tard.'],
  ['1944',
   'Ain',
   'Exécution de sept Juifs au cimetière de Rillieux',
   "Exécution des sept Juifs au cimetière de Rillieux le 29 juin 1944 par la milice française sous la responsabilité de Paul Touvier, en représailles à l'assassinat du secrétaire d'État à l'Information de Vichy Philippe Henriot, exécuté par des résistants (s'étant fait passer pour des miliciens), à Paris, le 28 juin 1944.",
   "Touvier est traqué pendant la Libération, il a réussi néanmoins à se cacher chez des amis. Double condamnation à mort à son rencontre en 1946 et 1947, il profite d'un défaut de surveillance pour s'évader. Il repart en cavale dans des réseaux catholiques, puis et finalement arrêté en 1989, jugé et condamné en 1994 à la réclusion criminelle à perpétuité. Il est le premier Français condamné pour crimes contre l'humanité. Touvier est également soupçonné d'avoir assassiné les époux Basch en 1944. Touvier meurt en prison en 1996 d'un cancer de la prostate généralisé à la prison de Fresnes à l'âge de 81 ans."],
  ['1944',
   'Hauts-de-Seine',
   'Affaire Barthélémy',
   'Assassinat de Georges Barthélémy, maire français, le 10 juillet 1944.',
   ''],
  ['1944',
   'Paris',
   'Affaire Van Aerden',
   'Assassinat de François Van Aerden, diplomate belge réfugié en France, dans des circonstances mystérieuses le 1er septembre 1944.',
   ''],
  ['1945',
   'Dieppe',
   'Tuerie de Dieppe',
   "En juin 1945, le caporal Abd el Maleck, tirailleur nord-africain en garnison, agresse une jeune femme à l'arme blanche puis, après s'être emparé d'un fusil, tire sur des passants pendant la nuit du 10 au 11 juin et la journée du 11 juin. Traqué par la police, la gendarmerie et des militaires, il est arrêté au Petit-Appeville après avoir causé seize morts (dont deux policiers) et plusieurs blessés.",
   'Abd el Maleck est capturé vivant et envoyé à Rouen pour être jugé par le Tribunal militaire.'],
  ['1945-1951',
   'Paris',
   'Gang des Tractions Avant',
   'Banditisme. Pierre Loutrel, dit «\xa0Pierrot le Fou\xa0», Émile Buisson, René Girier, dit «\xa0René la Canne\xa0»…',
   'Le gang inspire plusieurs films, dont Le Bon et les Méchants en 1976 et René la Canne en 1977.'],
  ['1946',
   'Indre',
   'Affaire Carteron',
   'Assassinat de la famille Carteron le 21 juillet 1946 aux «\xa0Ajoncs-Barrats\xa0» près de Bommiers.',
   ''],
  ['1946',
   'Indre',
   'Affaire Mis et Thiennot',
   'Assassinat de Louis Boistard, garde-chasse, le 29 décembre 1946 à Mézières-en-Brenne par Raymond Mis et Gabriel Thiennot.',
   "L'affaire est relancée en 1980 par la publication du livre de Léandre Boizeau, Ils sont innocents et la création d'un comité de soutien. Sous l'impulsion de ce comité, la loi sur la révision d'une condamnation pénale est modifiée à deux reprises en 1989 et 2021. Sept requêtes en révision rejetées entre 1983 et 2026."],
  ['1947',
   'Maine-et-Loire',
   'Affaire Leloy',
   "Assassinat d'Albert Leloy, le 10 décembre 1947 à Baugé à coups de hache, par son épouse Germaine.",
   'Elle est la dernière condamnée à mort exécutée en France.'],
  ['1950-1993',
   'Pas-de-Calais, Haute-Savoie',
   'Affaire Sydor',
   "Meurtre d'une prostituée, vers 1950, meurtre de sa femme et tentative de meurtre de son beau-père près de Lens, le 22 décembre 1961, enlèvement viol et assassinat de Jessica Blanc, 7 ans, à Vacheresse, le 25 juillet 1993, par Michel Sydor.",
   '«\xa0Le légionnaire\xa0»']],
 [['1951',
   'Guadeloupe',
   'Affaire Fengarol',
   'Assassinat supposé de Amédée Fengarol, 45 ans, maire de Pointe-à-Pitre en Guadeloupe le 11 janvier 1951.',
   ''],
  ['1951',
   'Paris',
   'Affaire Dubuisson',
   'Assassinat de Félix Bailly par son ex-amoureuse Pauline Dubuisson, étudiante en médecine, le 17 mars 1951.',
   "Cette affaire a inspiré le personnage du film La Vérité (film, 1960) d'Henri-Georges Clouzot."],
  ['1951',
   'Loiret',
   'Affaire Chevallier',

In [5]:
### On transforme les listes en DataFrames
import pandas as pd

liste_dataf = list()
for tableau in faitsDiv :
    liste_dataf.append(pd.DataFrame(tableau))

In [7]:
### On ajoute des titres aux colonnes

## On récupère les noms de colonnes

liste_colonnes = list()

for tableau in tableaux :
    table_body = tableau.find('tbody')
    rows = table_body.find_all('tr')
    for row in rows:
        cols = row.find_all('th')
        if len(cols) > 0 : 
            cols = [ele.get_text(separator=' ').strip().title() for ele in cols]
            liste_colonnes.append(cols)

## On rajoute les colonnes sur le data frame :

for i in range(len(liste_dataf)):
    liste_dataf[i].columns = liste_colonnes[i]

liste_dataf[5].head()

,Année [ Note 1 ],Département(S) [ Note 2 ],Affaire,Résumé,Condamnations Et Commentaires
0,1951,Guadeloupe,Affaire Fengarol,"Assassinat supposé de Amédée Fengarol, 45 ans,...",
1,1951,Paris,Affaire Dubuisson,Assassinat de Félix Bailly par son ex-amoureus...,Cette affaire a inspiré le personnage du film ...
2,1951,Loiret,Affaire Chevallier,"Assassinat, de Pierre Chevallier député et sec...",
3,1952,Alpes-de-Haute-Provence,Affaire Dominici,Meurtre de trois membres d'une famille anglais...,L'affaire inspire notamment L'Affaire Dominici...
4,1953,Pyrénées-Orientales,Affaire Marty,Empoisonnement supposé au gardénal de Jeanne C...,

In [13]:
### On concatène tout pour faire un gros tableau

faitsDivDF = pd.concat(liste_dataf)
faitsDivDF = faitsDivDF.reset_index(drop=True)

print(len(faitsDivDF))
faitsDivDF.head(15)

474

,Année [ Note 1 ],Département(S) [ Note 2 ],Affaire,Résumé,Condamnations Et Commentaires,Commentaires Et Condamnations
0,1905 - 1908,Drôme,Chauffeurs de la Drôme,"De 1905 à 1908 dans la Drôme, actes de brigand...",Urbain Liottard est condamné le 10 juillet 190...,NaN
1,1907,Seine,Affaire Soleilland,"Le 31 janvier 1907 à Paris, meurtre de Marthe ...",Albert Soleilland est condamné le 23 juillet 1...,NaN
2,1907,Gironde,Crime de Langon,"Le 6 février 1907 à Langon, assassinat crapule...",Jean-Eugène Branchery est condamné le 29 févri...,NaN
3,1909,Seine-et-Oise,Affaire Bourette,"Le 22 octobre 1909 au Vésinet, empoisonnement ...",Marie Bourette est condamnée le 13 juillet 191...,NaN
4,1910,Seine,Affaire Liabeuf,"Le 8 janvier 1910 à Paris, assassinat d'un pol...",Jean-Jacques Liabeuf est condamné le 4 mai 191...,NaN
5,1910,Seine-Inférieure,Affaire Durand,"Le 9 septembre 1910 au Havre, meurtre de Louis...",Jules Durand est condamné le 25 novembre 1910 ...,NaN
6,1911-1912,"Paris, Val-de-Marne, Val-d'Oise, Oise",La Bande à Bonnot,Série de braquages et de meurtres.,Les méfaits de la bande inspirent notamment un...,NaN
7,1913,Loire-Inférieure,Affaire Marcel Redureau,Meurtre de sept personnes le 30 septembre 1913...,"Condamné à 20 ans de prison, Marcel Redureau m...",NaN
8,1914,Finistère,Affaire Cadiou,"Le 4 février 1914, le corps de Louis Cadiou es...","Jugé cinq ans après les faits, l'ingénieur Lou...",NaN
9,1914,Paris,Affaire Caillaux,"Assassinat du directeur du Figaro, Gaston Calm...",Le président de la République fait une déposit...,NaN
10,1914,Paris,Affaire Villain,"Assassinat du leader socialiste Jean Jaurès, l...","Jugé cinq ans après les faits, Raoul Villain e...",NaN
11,1915-1919,Yvelines,Affaire Landru,Assassinat de onze femmes entre février 1915 e...,L'affaire inspire un film en 1947 de Charlie C...,NaN
12,1916,Algérie française,Affaire de Foucauld,"Assassinat de Charles de Foucauld, 58 ans, prê...",,NaN
13,1917-1922,Corrèze,Affaire du corbeau de Tulle,Vague de lettres anonymes signées « L'Œil de t...,Cette affaire a un retentissement national. Pi...,NaN
14,1920-1922,Paris,Affaire Bassarabo,Assassinat du commissionnaire Georges Bassarab...,Le crime et le procès firent la une de la pres...,NaN